import aoc_2024/day_8
import gleeunit/should

const input = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"

pub fn silver_2024_08_test() {
  input |> day_8.parse |> day_8.pt_1 |> should.equal(14)
}

pub fn gold_2024_08_test() {
  input |> day_8.parse |> day_8.pt_2 |> should.equal(34)
}
